import viewList2 from './views/000_viewList.vue'
import home from './views/001_home.vue'
import home_tel_dialog from './views/001_home_tel_dialog.vue'
import guide from './views/001_guide.vue'
import guide2 from './views/001_guide2.vue'
import guide_step from './views/100_guide_step.vue'
import login_fail from './views/001_login_fail.vue'
import notice from './views/002_notice.vue'
import notice_nodata from './views/002_notice_nodata.vue'
import notice_detail from './views/002_notice_detail.vue'
import kj_login from './views/003_login.vue'
import kj_registered from './views/003_registered.vue'
import kj_registered_info from './views/003_registered_info.vue'
import kj_registered_dialog1 from './views/003_registered_dialog1.vue'
import kj_registered_dialog2 from './views/003_registered_dialog2.vue'
import kj_registered_dialog3 from './views/003_registered_dialog3.vue'
import kj_registered_dialog4 from './views/003_registered_dialog4.vue'
import kj_password01 from './views/003_password01.vue'
import kj_password02 from './views/003_password02.vue'
import kj_password_dialog1 from './views/003_password_dialog1.vue'
import kj_password_dialog2 from './views/003_password_dialog2.vue'
import kj_password_dialog3 from './views/003_password_dialog3.vue'
import kj_entry_dialog1 from './views/004_entry_dialog1.vue'
import kj_entry_dialog2 from './views/004_entry_dialog2.vue'
import kj_entry_dialog3 from './views/004_entry_dialog3.vue'
import kj_entry_dialog4 from './views/004_entry_dialog4.vue'
import kj_exchange_guide from './views/005_exchange_guide.vue'
import kj_classDetail_directory from './views/005_classDetail_directory.vue'
import kj_classDetail_info from './views/005_classDetail_info.vue'
import kj_required_course from './views/005_required_course.vue'
import kj_required_course_view from './views/005_required_course_view.vue'
import kj_exchange_screening from './views/005_exchange_screening.vue'
import kj_exchange_study_qrcode from './views/005_exchange_study_qrcode.vue'
import kj_tryListen_directory from './views/005_tryListen_directory.vue'
import kj_tryListen_info from './views/005_tryListen_info.vue'
import kj_exchangepool_empty from './views/006_exchangepool_empty.vue'
import kj_exchangepool from './views/006_exchangepool.vue'
import kj_confirmOrder from './views/007_confirmOrder.vue'
import kj_confirmOrder_invoice from './views/007_confirmOrder_invoice.vue'
import kj_confirmPay from './views/007_confirmPay.vue'
import kj_paySuccess from './views/007_paySuccess.vue'
import kj_signUpList_noPay from './views/008_signUpList_noPay.vue'
import kj_credit_dialog from './views/008_credit_dialog.vue'
import kj_signUpList_paid from './views/008_signUpList_paid.vue'
import kj_signUpList_close from './views/008_signUpList_close.vue'
import kj_signUpList_refund from './views/008_signUpList_refund.vue'
import kj_orderDetail from './views/008_orderDetail.vue'
import kj_orderDetail_status from './views/008_orderDetail_status.vue'
import kj_order_qrcode from './views/008_order_qrcode.vue'
import kj_order_invoice from './views/008_order_invoice.vue'
import kj_refund_submit from './views/008_refund_submit.vue'
import kj_refundDetail from './views/008_refundDetail.vue'
import kj_refundDetail_status from './views/008_refundDetail_status.vue'
import kj_signUpList_changeRecord from './views/009_signUpList_changeRecord.vue'
import kj_signUpList_changeRecord_qrcode from './views/009_signUpList_changeRecord_qrcode.vue'
import kj_personalCenter from './views/010_personalCenter.vue'
import kj_personalCenter_info from './views/010_personalCenter_info.vue'
import kj_personalCenter_changePhone from './views/010_personalCenter_changePhone.vue'
import kj_personalCenter_password from './views/010_personalCenter_password.vue'
import kj_personalCenter_situation from './views/010_personalCenter_situation.vue'
import kj_personalCenter_situation_dialog from './views/010_personalCenter_situation_dialog.vue'
import kj_mask_select_box from './views/011_mask_select_box.vue'

import kj_courseSelectionTraining from './views/005_courseSelectionTraining.vue'
import kj_courseSelectionTraining_self from './views/005_courseSelectionTraining_self.vue'
import kj_courseSelectionTraining_helpme from './views/005_courseSelectionTraining_helpme.vue'
import kj_courseSelectionTraining_helpme_view from './views/005_courseSelectionTraining_helpme_view.vue'
import kj_courseSelectionTraining_quick from './views/005_courseSelectionTraining_quick.vue'

export default {guide,guide2,guide_step,login_fail,viewList2,home,home_tel_dialog,notice,notice_nodata,notice_detail,kj_login,kj_registered,kj_registered_info,kj_registered_dialog1,kj_registered_dialog2,kj_registered_dialog3,kj_registered_dialog4,kj_password01,kj_password02,kj_password_dialog1,kj_password_dialog2,kj_password_dialog3,
  kj_entry_dialog1,kj_entry_dialog2,kj_entry_dialog3,kj_entry_dialog4,kj_exchange_guide,kj_classDetail_directory,kj_classDetail_info,
  kj_required_course,kj_required_course_view,kj_exchange_screening,kj_exchange_study_qrcode,kj_tryListen_info,kj_tryListen_directory,kj_exchangepool_empty,kj_exchangepool,
  kj_confirmOrder,kj_confirmOrder_invoice,kj_confirmPay,kj_paySuccess,kj_signUpList_noPay,kj_credit_dialog,kj_signUpList_paid,kj_signUpList_close,kj_signUpList_refund,kj_orderDetail,kj_orderDetail_status,kj_order_qrcode,kj_order_invoice,
  kj_signUpList_changeRecord,kj_personalCenter,kj_personalCenter_info,kj_personalCenter_changePhone,kj_personalCenter_password,kj_courseSelectionTraining,kj_courseSelectionTraining_self,
  kj_courseSelectionTraining_helpme,kj_courseSelectionTraining_helpme_view,kj_courseSelectionTraining_quick,kj_personalCenter_situation,kj_personalCenter_situation_dialog,kj_mask_select_box,kj_signUpList_changeRecord_qrcode,kj_refund_submit,kj_refundDetail,kj_refundDetail_status
}
